### ISSUE TITLE
Forum is down

### ISSUE THREAD

**Issue by StoneOffStones** [Lynx187/plugin.video.xstream#100]
Hallo Lynx187,

natürlich ist es nicht gänzlich an uns vorbeigegangen das, dass Forum seit gestern Nachmittag nicht mehr online ist.
Stelle dieses Issue nicht aus Langeweile oder Neugier ein sondern aus dem Hintergrund das die User bereits teilweise uns über die Beta/Nightly fragen was aktuell los ist.
Leider kennen auch wir die Hintergrunde nicht im Detail und hoffen nur das es ein kleines/großes Update für die xStream Webseite gibt.

Kannst du eventuell etwas Licht ins dunkle bringen?

**Comment by Lynx187** [comment]
Das Konto wurde deaktiviert warum weiss ich auch noch nicht, mal schaun.

**Comment by StoneOffStones** [comment]
Ach du meine Güte!
Sind jetzt alle Daten pfutsch?

**Comment by Lynx187** [comment]
wenn es reaktiviert wird nicht ansonsten hätte ich noch nen db stand vom 14.3.

**Comment by StoneOffStones** [comment]
Na dann hoffen wir mal das Beste...

**Comment by Kukolorus** [comment]
Wie lange wird es denn dauern bis wir das Forum wieder nutzen können? Also voraussichtlich...

**Comment by rene1980** [comment]
Könnt Ihr nicht die Daten auf einen Neuen Server aufspielen und notfalls ne neue Seite.Könnte es sich um Serverwartungsarbeiten handeln?Das gabs bei Kodinerds auch mal.

**Comment by bombaygin** [comment]
rip

**Comment by Lynx187** [comment]
Ok ich weiss inzwischen das Warum: es wurden ungewöhlich viele Mails versendet. Dadurch wurde angenommen dass Spam versendet wird und somit automatisch die Seite deaktiviert. Jetzt müsste ich schaun ob der Code tatsächlich kompromittiert wurde und es ggf. bereinigen. Echt K.A. ob ich darauf noch Lust habe.

**Comment by StoneOffStones** [comment]
Alternative wäre das Backup laden?!
Besteht da nicht ebenfalls die Gefahr, dass "Rückstände" im Code enthalten sind?

Muss sagen, gerade in den letzten Wochen ist extrem viel im Forum passiert.
Es wäre wirklich schade wenn alles weg wäre...

**Comment by Lynx187** [comment]
Es ist ein DB Backup da ist kein Code enthalten.

Die Alternative ist nicht einfach nur das Backup zu nehmen sondern generell nicht mehr über das Forum zu supporten.

**Comment by StoneOffStones** [comment]
Ok...

und dann alles über GitHub laufen lassen?!
Dann müsste man die Readme/Wiki einmal sauber pflegen/erstellen. Über die AutoUpdate Funktion ist würde vieles (Probleme im Addon) von selbst gelöst werden.
Und alle die sich aktiv daran beteiligen wollen würden sich dann Issues in GitHub erstellen.

Könnte man machen, die Frage ist aber ob das so ausreicht.

**Comment by StoneOffStones** [comment]
Was denken die anderen fleißigen dazu?!

**Comment by Lynx187** [comment]
Nach 4 oder 5 Jahren mit meistens den selben Fragen ist es mir ehrlich gesagt langsam egal ob das für alle ausreicht. Es hält einfach vom wesentlichen ab und verursacht Kopfschmerzen.

**Comment by seberoth** [comment]
Das stimmt. Es gab im großen und ganzen nur 2 arten von Threads im Forum.

1. xyz funktiniert nicht mehr (wofür man auch den Issue Tracker nehmen kann)
2. Wie installiere ich xStream auf xyz?

Und halt zwischendurch noch Seitenvorschläge (Vom Dev Bereich mal abgesehen)

**Comment by StoneOffStones** [comment]
Na dann geht es halt hier fröhlich weiter.
Ich muss auch ehrlich gestehen, dass man es nicht negativ bei der Weiterentwicklung im rahmen der Beta/Nightly gemerkt hat. 

Um trotzdem fragen nach Charakter Nr.2 zu beschränken sollte eine vernünftige ReadMe+Wiki nicht fehlen. Dann kann man immer schön drauf verweisen und gut ist!

**Comment by netzgeist** [comment]
Nutzt doch reddit für Communitykram und github als Quelle für Binaries und Wiki. Beide Parteien zeichnen sich weniger durch vorrauseilenden Gehorsam aus als blaced :palm_tree: 

 /r/XStream ist frei (habs nun belegt und reiche es auf Anfrage durch)

**Comment by Lynx187** [comment]
Ist logisch dort kann man ja auch keine eigene Website hosten sondern muss das nehmen was da ist.

**Comment by rene1980** [comment]
Heißt dann,die Kommunikation läuft dann innZukunft hier über github?

**Comment by StoneOffStones** [comment]
Hatte sowieso schon damit begonnen die Readme in der Beta/Nightly zu aktualisieren.
Da war noch viel auf XBMC und auf eine veralteten Site-Plugin Stand bezogen.

**Comment by bombaygin** [comment]
das ist aber meiner Meinung nach etwas blöd das es nur über Github läuft da viele das garnicht verstehen hier mit Github. (und ein Pech gehabt wäre jetzt unangebracht!)
xStream ist das einzige deutsche Kodi Addon (und natürlich das Beste) und ich finde es unfair wie es behandelt wird. Es hat ein eigenes Forum verdient oder wenigstens eine Reddit Rubrik oder so wo man wenigstens etwas Kommunikation hat da nicht jeder mit Github klarkommt.

**Comment by shagger** [comment]
Hallo, 
Es wäre zwar schade, das es kein Forum gäbe...
Verfolge  auch weiterhin hier bei github.
Auch wenn es manchmal nervig ist, die gleichen fragen zu beantworten.....Bleibt weiter am ball.
Tolle Arbeit und support.
