### ISSUE TITLE
Burning Series implementation broken.

### ISSUE THREAD

**Issue by netzgeist** [Lynx187/plugin.video.xstream#102]
Kodi Isengart, XStream aktuell aus Superrepo. 

Starte XStream. navigiere zu BS. Versuche eine Kategorie zu öffnen. XStream fehlert aus mit:

     Type Error: String indices must be integer.

Nutze einen bereits favorisierten Link zu seinem Stream (oder einer Staffel) aus dem Favoritenmenü. XStream fehlert aus mit:

     Key Error 'series'

**Comment by Viper2k4** [comment]
https://github.com/StoneOffStones/plugin.video.xstream/issues/28
