### ISSUE TITLE
SSL und Python >= 2.7.9

### ISSUE THREAD

**Issue by seberoth** [Lynx187/plugin.video.xstream#106]
Hi,

hab leider grad kein git zurhand. Könntest du da mal drübergucken und wenn es in Ordnung ist mit reinnehmen?

War zwar nur ein Test ohne Kodi, sollte sich ja aber 1:1 übernehmen lassen.

https://gist.github.com/seberoth/1007aed03cd81c665d1871adef684791

EDIT: Getestet mit Python 2.7.10

**Comment by sraedler** [comment]
Dein Gist url ist defekt... 404

**Comment by seberoth** [comment]
Seltsam... Geht nun wieder.

**Comment by Lynx187** [comment]
ja jetzt ist ja auch wieder die 1 am ende ;-)

**Comment by seberoth** [comment]
Hab sie beim Edit wohl mit weggehauen.

Wie gesagt, der Pathc wurde wohl anscheinend mit in 2.7.11 integriert, weshalb "nur" 9 und 10 betroffen sind.

Sollte man aber trotzdem mit reinnehmen, da Kodi 17 ja anscheinend (zumindestens auf manchen betriebssystemen) damit laufen wird

**Comment by Lynx187** [comment]
Ok das würde jetzt erst mal gar nicht mehr verifizieren aber das ist für xStream auch erst mal irrelevant.

**Comment by seberoth** [comment]
Ansich bin ich mit der Lösung auch nicht zufrieden (Sicherheit & Co). Aber es ist wohl der einzige Workaround dafür.

**Comment by Lynx187** [comment]
Hab übernommen werden ja keine wichtigen Daten übertragen.
