### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by Jawler** [Lynx187/plugin.video.xstream#112]
It seems like the version number is not changing very often. Some updates will reach the useres very late. For example there was no increase in the version number aftrer the fix for the new URL Resolver. 
Also there seems to be a typo in the addon.xml for the repo. It says `  <info ompressed="false">` in line 8.

**Comment by Jawler** [comment]
Okay. So i just looked at the latest pull requests and realized, that there is some kind of auto updater. But the code looks like (i'm not into python) it also checks only version number. What does it actually do?

**Comment by Lynx187** [comment]
Yes that's a typo, but it is in the other repository and it is just referring to the older repo for Kodi.
The version number in this repository here is not checked by Kodi, so it does not matter for now.

As the name says it performs updates. The source for the updates is determined by the choosen option. For two options it checks the version number for the third option it checks the latest commit.
