### ISSUE TITLE
hdfilme.tv browsercheck redirect

### ISSUE THREAD

**Issue by Dostron** [Lynx187/plugin.video.xstream#142]
Wie es aussieht hat hdfilme.tv ganz neu einen Browsercheck mit einem Redirect auf die Hauptseite eingebaut, um wahrscheinlich solche tollen Addons wie dieses zu blocken.
Es werden dann auch Cookies abgelegt, die den Check belegen, damit er nur einmal durchgeführt wird.

**Comment by Jeycop** [comment]
Lässt sich dieser derzeitige "Error 503" irgendwie mit Kodi umgehen?
Bzw. ist oder wird es jemals wieder möglich sein, von hdfilme.tv über Kodi zu streamen?

**Comment by Dostron** [comment]
Sollte machbar sein. Ist aber nicht so einfach und mit Arbeit verbunden.
Leider ist Python nicht meine Programmiersprache und ich kann nicht helfen. Mit PHP wüsste ich wie man das umgehen kann.
Die Frage ist wer nimmt sich dem Problem an. Es wäre sehr schade den hdfilme.tv zu verlieren.

**Comment by Ar1i** [comment]
Der Anbieter, ist halt einer mit der besten Qualität würde ich mal so sagen. Ich schaue mir das ganze mal an, kann aber für nichts garantieren, da ich in Python nicht der beste bin.

**Comment by Dostron** [comment]
Python ist nicht so schwer, aber eine IDE Umgebung aufzubauen mit der man Kodi Addons programmieren kann ist nicht ohne. Ich hab's mir vor ein paar Wochen mal angesehen.
Danke Dir Ar1i. 
P.S. Wenn ich Dir irgendwie behilflich sein kann, gerne.

**Comment by Ar1i** [comment]
@Dostron wenn du mir sagen kannst, wie ich bsp js2py auf kodi kriege, dann hätte ich ne lösung :p Aber Keine Ahnung, beschäftige mich das erste mal gerade damit.

**Comment by sraedler** [comment]
Das einrichten einer Umgebung ist nicht so schwer.

Einfach das plugin in Pycharm laden (ist im ordner %appdata%\Kodi\addons\plugin.video.xstream)

Anschließend die "pycharm-debug.egg" aus C:\Program Files (x86)\JetBrains\PyCharm 2016.2\debug-eggs in den ordner %appdata%\Kodi\addons\plugin.video.xstream kopieren (natürlich entpackt)

Dann einen Remotedebugger in Pycharm hinzufügen und die angegebenen Zeilen beim starten des debuggen starten

Sind circa so 

> import pydevd
pydevd.settrace('localhost', port=6799, stdoutToServer=True, stderrToServer=True)

Natürlich mit dem Angegebenen Port.

vllt. klappt es schon so...

Evtl. mach ich in den nächsten Tagen ein Tutorial mit Screenshots.

**Comment by Dostron** [comment]
@Ar1i  Javascript da könnte ich helfen, aber die Pythoneinbindung... Da muss ich auch recherchieren.
@sraedler Könntest Du Ar1i bei js2py einen Tipp geben, wenn Du Kodi Addon sattelfest bist?
@sraedler #Entwicklungsumgebung Wenn Kodi bereits auf Windows läuft, ja. Bei mir läuft das Kodi auf einem lokalen Multimedia Linuxserver. Äh "Server" PC... ;-) D.h. erst mal Kodi auf meine Entwicklungskiste installieren. Da laufen aber schon 2 Entwicklungsumgebungen und 3 Datenbanken, die ich für die Arbeit brauche. Könnte aber meinen alten Laptop zum Kodi basteln rauskramen. Hört sich wirklich nicht so schwer an. Das Tutorial, dass ich gelesen haben ging über Eclipse IDE und Python Einbindung und und und...
Habe auch nicht damit gerechnet, dass ich anfange Addons zu bauen. Wollte einfach ein Multimedia System in der Stube. ;-)

**Comment by Viper2k4** [comment]
@Ar1i du hier ^^

Das Problem mit Cloudflare ist schlicht und ergreifend das sie auch Änderungen durchführen die dann quasi wie ein CodeBreake agieren. Am liebsten wäre mir irgendwie ein Projekt zu missbrauchen damit wir uns quasi nicht das Problem ans Bein binden. Wie im Forum schon geschrieben gibt es ja einige Addons die sowas eingebaut haben.

Wenn wir was Funktionierendes haben würde ich das Ganze aber aus HDFilme.TV raushalten und eher direkt in den `cRequestHandler` reinhauen. Einfach weil es ein paar Seiten gibt (ggf. auch in der Zukunft) die mit Cloudflare arbeiten. Dann hätten wir die Funktion an zentraler Stelle.

Ich arbeite btw. komplett ohne DEV-Umgebung mit Notepad++ :)

**Comment by sraedler** [comment]
@Viper2k4 sieht sehr nach nur kopiert aus...

Hab jetzt mal zwei Stunden versucht das ganze irgendwie automatisch zu installieren, das geht aber nicht so leicht, da kodi pypi nicht unterstützt.

Um das ganze zum laufen zu bringen müsste also Sessions und Js2Py in die resourcen aufgenommen werden, was ich nicht schön finde...

alternativ ein "Cloudflarebypass" addon für kodi schreiben und das einreichen in die offizielle repo und dies anschließend als dependency in das addon laden.

bin mir aber auch noch nicht so ganz sicher wie es am einfachsten wäre, da muss ich erst noch drüber nachdenken

**Comment by Ar1i** [comment]
@Viper2k4 haha was ein Zufall.
Naja, würde sagen das https://github.com/Anorov/cloudflare-scrape weiterhelfen würde. Schaue mir das mal an wenn ich Zeit habe mit js2py, da dass natürlich am einfachsten wäre. Und bevor das mit in den Request Handler eingebaut wird, würde ich vorerst nur HDFilme damit betreiben.

**Comment by Viper2k4** [comment]
@sraedler ja Js2Py als Kodi-projekt wäre natürlich perfekt. Am besten noch im offiziellen Repro. Die Frage ist nur wie ^^. Issue bei den auf der Seite machen und fragen? ^^

Ich würde es wie folgt vorschlagen:

**Step 1**

- cloudflare-scrape + js2py  direkt in xStream einbauen 
- Requests als Abhänigkeit einbinden 
- erstmal nur bei HDFilme.TV verwenden

In dieser Stage wäre xStreame erstmal etwas vollgeladen aber HDFilme würde wieder laufen.

**Step 2**

- cloudflare-scrape + js2py Addons-Pakete für Kodi bauen und in die xStream-Repo packen
- Requests Abhänigkeit ins "cloudflare-scrape"-Addon packen
- Verarbeitung in cRequestHandler auslagern

Hier wäre xStream wieder sauber soweit jedoch haben wir noch den Pflege-Aufwand der Addons

**Step 3**

- den schwarzen Peter weiter scheiben und die Addons von wo anders aktuallisieren lassen ^^

**Comment by Viper2k4** [comment]
So habe es zum laufen bekommen. Aber noch nicht ganz perfekt. Das erstmal der erste Versuch. Aktuell läd er bei jedem Webseiten Requerst 5sekunden. Aber naja besser so als garnicht^^

**Comment by Viper2k4** [comment]
Hat schon mal jemand mit den Cookies im Requesthandler gearbeitet? Weil sonst könnte man nämlich den Cloudflare cookie bekomme mit:

```
# Get CloudFlare-Cookie
scrapper = cfscrape.CloudflareScraper()
cookie_value, user_agent = scrapper.get_cookie_string(URL_MAIN)
```

Den cookie-string und user_agent könnte man dann bei den Parms mit übergeben und dann bei jeden Aufruf mitgeben. So bräuchte man nur 1x 5sekunden warten und müsste nicht jedes mal warten. Wäre einfacher wenn wir instancen hätten, aber naja man nimmt was man hat :)

**Comment by Lynx187** [comment]
```
cookie = requestHandler.createCookie(name,value,domain=domain, expires=<integer timecode des datum oder sehr großes int>, discard=False)
requestHandler.setCookie(cookie)
```

**Comment by Viper2k4** [comment]
ne Minute früher hatte ich es jetzt so gelöst erstmal:

https://github.com/StoneOffStones/plugin.video.xstream/commit/8ca893c9b2e557adb4a6c1e629a455267e5abae0

Die Frage ist halt wie wir weiter vorgehen. Zurzeit haben wir uns extrem viel balast mit an bord gezogen. Wenn wir beschleißen das wir das drin behalten könnten wir auch Änderungen vor nehmen. Wenn nicht müssen wir mir den Leben was wir haben :/

**Comment by Viper2k4** [comment]
So bin erstmal raus für heute. HF in der nightly wenn wir ne Idee habt :)

**Comment by Viper2k4** [comment]
Ok konnte es doch nicht lassen. Das Problem mit Kodi 16 lies sich beheben indem man die Version von hier nimmt:

https://github.com/ramicspa/kodi/tree/master/plugin.video.LivePolishTV/lib/js2py

Bis jetzt scheint es zu laufen. Einziges Problem zurzeit sind die Cover. Da diese natürlich auch hinter Cloudflare stecken und Kodi damit nicht um kann werden leider keine Bilder geladen :/

**Comment by Viper2k4** [comment]
@Lynx187 So ich überlege grade ob ich den Scrapper umbaue das er de Requesthandler benutzt. Nur für mein Verständniss. Ich würde request.sessions durch den requesthandler ersetzen. Muss ich den Cookie trotzdem von Hand erzeugen oder passiert dies Automatisch (nicht weiter reingeguckt).

**Comment by brepo33** [comment]
das nightly ging jetzt bis vor 1 std, denke hdfilme hat jetzt wieder etwas umgestellt.
mir ist bei der browservariante aufgefallen, das ein mackeeper popup kommt. evtl hat es etwas damit zu tun.

**Comment by brepo33** [comment]
komischerweise geht es jetzt wieder

**Comment by Ar1i** [comment]
@brepo33 die haben nichts umgestellt. Das ist einfach die Cloudflare Layer7 DDoS Protection. Deswegen der 5 Sekunden check.

**Comment by seberoth** [comment]
Hab mal spa­ßes­hal­ber ein bisschen rumgespielt. Ist zwar nicht optimal aber man könnte sich den js2py kram sparen:

https://gist.github.com/seberoth/cde4c6edab29cf67cd641fbf2fadff01

**Comment by Viper2k4** [comment]
Habe ich auch schon dran gedachte als ich das hier gesehen habe:

https://github.com/elcattivo/CloudFlareUtilities/blob/master/CloudFlareUtilities/ChallengeSolver.cs

Wobei js2py garnicht das Problem ist. Wenn wir requests.sessions raus bekommen wäre es viel cooler. Am liebsten hätte ich den Scrapper part nämlich direkt im requesthandler so das, sich klein Plugin um die angelegenheit mit den Cookies kümmern muss.

**Comment by Viper2k4** [comment]
Habe jetzt btw. was gefunden um auch Cookies and Kodi weiterzuleiten. Dadurch können wir auch bei Cloudflare-Seiten Bilder anzeigen.

Aber wir müssen das echt in den Requesthandler oder als lib einbauen. Da die Plugins wirklich nichts machen müssen. Und das z.b bei Thumbnail automatisch die URL angepasst wird wenn die Seite Cloudflare hat usw.

Wir könnten btw. die ganze Cloudflare abfragen in den Requesthandler packen grob in Zeile 110. Das wir bei 503 usw. mal ne Cloudflare prüfung machen usw.

**Comment by seberoth** [comment]
Ist zwar nicht grade ideal, aber...
(Bitte den Kommentar oben beachten:)

https://gist.github.com/seberoth/bec4859217d2db55d93335d5777e9cbc

**Comment by Viper2k4** [comment]
@Dostron 
Ich denke das Issue könntest schließen. Ist zwar noch nicht im stable Build. Ich denke in der nächsten Version sollte es mit drin sein.

**Comment by Dostron** [comment]
Bin nicht ganz auf dem neusten Stand, war offline (Ferien). So wie ich alles überflogen habe, funzt HDFilme wieder. Allerdings sollte früher oder später das Ganze in den Request Handler ausgelagert werden.
Sobald die nächste Site Cloudflare benutzt, wird das sowieso wieder ein Thema. Ich lasse die Issue noch kurz offen und schliesse dann. Tks2U

**Comment by Dostron** [comment]
Tks2All
