### ISSUE TITLE
StreamCloud lädt lange wenn nicht verfügbar

### ISSUE THREAD

**Issue by SphaeroX** [Lynx187/plugin.video.xstream#143]
Der Timeout für StreamCloud sollte herab gesetzt werden. Wenn man den Hoster auswählt und das Video nicht erreichbar ist dauert es sehr lange bis eine Fehlermeldung kommt.

In der Fehlermeldung steht man soll in den Logs schauen, wie auch immer der Timeout sollte schneller passieren. Bei über 10 Links dauert es ewig einen guten zu finden, auch in Automatikbetrieb.

**Comment by Lynx187** [comment]
xStream hat darauf keinen Einfluss, vorausgesetzt die Verzögerung kam tatsächlich durch den Hoster zustande, was man mangels Log nicht 100%ig nachvollziehen kann.

**Comment by SphaeroX** [comment]
Hat es dort einen regex drin von wegen "Video nicht gefunden" oder sowas?

Oder wie erkennt er gelöschte Videos?

**Comment by Lynx187** [comment]
https://github.com/tknorris/script.module.urlresolver/blob/master/lib/urlresolver/plugins/streamcloud.py

**Comment by SphaeroX** [comment]
https://goo.gl/photos/FJiFKxNxdUzG6L8f8

hat es damit vielleicht was zu tun?
Weil StreamCloud gehen irgendwie alle nicht.

**Comment by sraedler** [comment]
Bei mir geht StreamCloud...
ohne Probleme...

**Comment by SphaeroX** [comment]
Okay kannst mir noch sagen wo ich die Logs finde? Dann Schau ich da nochmal nach und schließe hier

**Comment by Lynx187** [comment]
Nein der Countdown ist normal und dass er übersprungen wird sollte keine Problem bereiten.
Log: http://lmgtfy.com/?q=kodi+log

**Comment by SphaeroX** [comment]
Also ich habe jetzt mehrere Hoster getestet, bei vielen gibt es diesen Error

> 13:22:45 599.670532 T:1750352880   ERROR: URLResolver: Resolver Error: File not found 

Wenn ich dir URLs im Browser aufrufe ist aber alles okay, so auf die kürze betroffen sind:

- flashx
- divxstage 
- openload 
- promptfile 
- nowvideo 

StreamCloud geht

**Comment by StoneOffStones** [comment]
Stell doch einfach deinen Log bereit und dann das Problem weiter/näher beleuchtet werden!

**Comment by SphaeroX** [comment]
Die Log steht ja bereit nur ohne URL. Mehr Fehlermeldung gibt es auch nicht und kann damit auch nicht weiter dienen. 

Bin denn nur ich davon betroffen?
Wenn ja muss ich mal den HTML Quelltext separat abspeichern was denn überhaupt ausgegeben wird und wieso der regex nicht erkannt wird.

**Comment by Lynx187** [comment]
Im dem Log  (vorzugsweise mit debug logging) steht zumindest noch die Urlresolverversion, nach der man jetzt separat fragen muss... wie so oft.
Aber genrell garantiert niemand, dass immer alle resolver funktionieren.

**Comment by SphaeroX** [comment]
URLResolver: Initializing URLResolver version: 2.10.0

Benutze die Nightly von xstream

**Comment by Lynx187** [comment]
https://github.com/Lynx187/plugin.video.xstream#34-fehler-bei-verwendung-einiger-hoster

**Comment by SphaeroX** [comment]
Danke, kannst du noch erklären wie ich den bei xstream aktualisiere?

Habe die Version 3.0.9 als Addon installiert aber xstream verwendet immer noch 2.1.0

**Comment by Lynx187** [comment]
Du hättest lieber den ersten Punkt machen sollen (TVA Repo) und ggf. neustarten, zwar eigentlich nicht nötig aber auch nicht verkehrt.

**Comment by SphaeroX** [comment]
Nach dem Reboot ging es, lag wohl daran. 

Vielen Dank.
