### ISSUE TITLE
Cloud Flare Protection on hdfilme.tv

### ISSUE THREAD

**Issue by JnsDornbusch** [Lynx187/plugin.video.xstream#144]
Zurzeit funktioniert die Wiedergabe der Website hdfilme.tv nicht mehr,
da diese Seite nun Cloud Flare Protection benutzt und jede Abfrage vom Addon als Fehler gewertet wird.
Gibt es dafür eine Lösung?

**Comment by breaksrmine** [comment]
In den Einstellungen die nightly version wählen, dann geht's. In der stable/beta ist die Änderung noch nicht implementiert
