### ISSUE TITLE
TypeError in hoster.py

### ISSUE THREAD

**Issue by xiberger** [Lynx187/plugin.video.xstream#17]
first of all the log:
http://pastebin.com/xU3JrQjr

good job guys, works like a charm on my raspberry pi, but since the update to the new version I can not open a stream after searching for a series and selecting an episode - it simply loads until 60% and then crashes (line 47, caused by line 310 in hoster.py)

hope you guys can fix it soon - my python skills are not that good to fix it myself :)

**Comment by xiberger** [comment]
update: there is no hoster for the particular stream in the logfile - but would still be great to get an error message :D

**Comment by Lynx187** [comment]
fixed in 073a2a835a8d78c47d66c93a21995faf9ad4eda5
