### ISSUE TITLE
Suche auf movie4k mit wildcards

### ISSUE THREAD

**Issue by erik78** [Lynx187/plugin.video.xstream#19]
Hallo,
ich habe festgestellt, dass bei der Suche unter movie4k der Suchbegriff nur vom Anfang an gesucht wird. Als Beispiel:
Suchbegriff: haus 
Das Haus > wird nicht gefunden
Hausmeister Krause > wird gefunden
Im weissen Haus > wird nicht gefunden

Lösen kann man das für die movie4k Seite in dem man um das Suchwort ein % macht > %haus%. Mit dieser Methode findet man alle o.g. Beispiele.

Vielleicht kannst Du das mal selbst testen und ggf. erweitern.

**Comment by Lynx187** [comment]
Umgesetzt mit 205bc370763e990f3bdb311fd5fcd45fb61f572f
