### ISSUE TITLE
Gstream HD section Next page and Go To not working

### ISSUE THREAD

**Issue by Lynx187** [Lynx187/plugin.video.xstream#20]

**Comment by Lynx187** [comment]
Gstream - HD section - Next page and Go To just gives an empty list

**Comment by krellsebastian** [comment]
Should be fixed with #23 
Seems they changed the way to navigate between the resultpages when searching for HD. There's now a searchid generated as far as i investigated.

**Comment by merlux** [comment]
Should be fixed with #23. 
Seems they changed the way to navigate between the resultpages when searching for HD. There's now a searchid generated as far as i investigated.
