### ISSUE TITLE
 "ValueError No JSON could be decoded" when starting xStream

### ISSUE THREAD

**Issue by Lynx187** [Lynx187/plugin.video.xstream#21]
Sometimes the pluginDB gets corrupted and cannot be loaded.

**Comment by merlux** [comment]
Any way to reproduce this? Or some circumstances that this will happen more likely? haven't seen that error yet.

**Comment by Lynx187** [comment]
Not sure what is causing this, so just create a new one if loading fails.
https://github.com/Lynx187/plugin.video.xstream/commit/8deecee3722ae2f1777aa12161aae4f089f7e539
