### ISSUE TITLE
[Bugfix] Fix für Urlresolver inkompatibilität

### ISSUE THREAD

**Issue by FloFri** [Lynx187/plugin.video.xstream#28]
Hallo,

ich habe einen Bugfix gefunden, um die Inkompatibilität mit dem neuen Urlresolver zu fixen. Ich meine damit das Problem "no supported Hoster available" wenn "Hosterliste prüfen und sortieren" aktiviert ist. Da es nur eine Zeile ist, will ich hier keinen Pull Request machen.

In der Funktion "__getPriorities" (resources/lib/gui/hoster.py) folgende Zeile direkt nach "import urlresolver" hinzufügen:

urlresolver.lazy_plugin_scan()

Dadurch werden alle Plugins geladen, sofern das noch nicht geschehen ist. Damit ist dann auch die "implementators"-Liste gefüllt.

**Comment by Lynx187** [comment]
Jo weiss ich, hatte aber wegen weitere Änderungen an der betreffenden Datei noch keinen Commit gemacht.
Trotzdem danke.
