### ISSUE TITLE
"ValueError No JSON could be decoded" when using kodi favourites

### ISSUE THREAD

**Issue by mm1234** [Lynx187/plugin.video.xstream#30]
I'm receiving this Error message when trying select an item of my kodi favourites list. I use them as shortcut to my bs.to series
This worked flawless before 2.1.13
Seems to work if I create a new favorite entry, but I'd prefer fixing my existing favorite list as it has 50 entries.
I already tried to compare the favorites.xml old entry vs new entry but i don't really understand the syntax of the xml file.

P.S.: I've seen there's been an issue with same error message, but I wasn't able to see any coherences.
      If it's the same random error, how do i reset the mentioned pluginDB?

**Comment by Lynx187** [comment]
No sry this has nothing to do with the pluginDB.
The plugin now uses the bs.to api, which delivers JSON encoded data.
So, the plugin exspects JSOn data when ist requests the urls.
The urls in your favorites do not deliver JSON encoded data, which is causing this error.
You could replace the urls with the corresponding api urls.

**Comment by mm1234** [comment]
Ok, so is there a way to convert the existing links to the new JSON api links by just reading the favorites.xml? I'd prefer to repair the broken links in the favourites file over searching for 50 series and adding them back to the favourites manually... ;)

Thanks in advance

**Comment by Lynx187** [comment]
Well, yes but without some scripting skills ist would require more effort than creating 50 new favourites.
The url was something linke this: ...//burning-seri.es.to/serie/<series-name>
The new one is: ...//bs.to/api/series/<series-id>
So you have to replace the the part in front of <series-name> with bs.to/api/series/ , this is the easy part.
Then you have to replace <series-name> with the corresponding <series-id>, which would be very time consuming without a script.
You can get the names with the ids for all series from bs.to/api/series/.
