### ISSUE TITLE
Broken links in 2.1.13, xbian on raspberrypi2

### ISSUE THREAD

**Issue by ArcTanH** [Lynx187/plugin.video.xstream#32]
Switched conversation from commit-comments to issues, referencing commit d7dd9ab5b803c5e3b1e381ee5e039633cc8f3e1e

Summary: Opening streams results in 
```
ERROR: Open - Error opening http://www.hoster.com/file/ENCODEDFILEIDHERE=|User-Agent=Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.9.0.3) Gecko/2008092417 Firefox/3.0.3

ERROR: CDVDPlayer::OpenInputStream - error opening [http://www.hoster.com/file/ENCODEDFILEIDHERE=|User-Agent=Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.9.0.3) Gecko/2008092417 Firefox/3.0.3]
```
This affects any link, so in the plugin is completely broken in this version. Last working version is 2.1.12.

[updated] using markdown

**Comment by Lynx187** [comment]
Ok but only a problem with xbian.
Could you change the hoster.py to send the link without this UserAgent and then try to play a cloudyvideo stream via xstream?

**Comment by ArcTanH** [comment]
Good point. Does not change anything, so it fails anywhere else :( 
Heres some more log output for clarification. hope this helps?

```
NOTICE: -->Python Interpreter Initialized<--
NOTICE: *---- Running xStream, version 2.1.13 ----*
NOTICE: 	[xStream] ->kinox_to: {'function': 'parseMovieEntrySite', 'thumb': 'http://image.tmdb.org/t/p/w342/8BrcyoKEgGmRFHgi9dtWvrLDEfE.jpg', 'title': '[hidden]', 'imdbID': '[hidden]', 'sUrl': 'http://kinox.to/Stream/[hidden].html', 'site': 'kinox_to', 'mediaType': 'movie', 'sNewsTitle': 'Neue Filme online vom 09.07.2015', 'playMode': 'play', 'MovieTitle': '[hidden]', 'page': '1'}
NOTICE: 	[xStream] ->kinox_to: read html for http://kinox.to/Stream/[hidden].html? from cache
NOTICE: 	[xStream] ->kinox_to: http://kinox.to/aGET/Mirror/[hidden]&amp;Hoster=56&amp;Mirror=3
NOTICE: [{'resolved': False, 'streamUrl': 'http://www.promptfile.com/l/[hidden]'}]
NOTICE: URLResolver: Initializing URLResolver version: 2.9.0.0.1
NOTICE: URLResolver: No Settings Update Needed
NOTICE: 	[xStream] ->kinox_to: call play: http://www.promptfile.com/l/[hidden]
NOTICE: 	[xStream] ->kinox_to: file link: http://www.promptfile.com/file/[hidden]=
NOTICE: 	[xStream] ->kinox_to: start player
NOTICE: 	[xStream] ->kinox_to: player instance created
NOTICE: DVDPlayer: Opening: http://www.promptfile.com/file/[hidden]=
WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
NOTICE: Thread DVDPlayer start, auto delete: false
NOTICE: Creating InputStream
ERROR: Open - Unhandled exception
ERROR: Open - Error opening http://www.promptfile.com/file/[hidden]=
ERROR: CDVDPlayer::OpenInputStream - error opening [http://www.promptfile.com/file/[hidden]=]
NOTICE: CDVDPlayer::OnExit()
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.xstream/?site=kinox_to&function=parseMovieEntrySite&title=[hidden]&thumb=http%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Fw342%[hidden].jpg&imdbID=[hidden]&sUrl=http%3A%2F%2Fkinox.to%2FStream%2F[hidden].html&mediaType=movie&sNewsTitle=Neue+Filme+online+vom+09.07.2015&playMode=play&MovieTitle=[hidden]&page=1]
NOTICE: CDVDPlayer::CloseFile()
NOTICE: DVDPlayer: waiting for threads to exit
NOTICE: DVDPlayer: finished waiting
NOTICE: CDVDPlayer::CloseFile()
NOTICE: DVDPlayer: waiting for threads to exit
NOTICE: DVDPlayer: finished waiting
```

**Comment by Lynx187** [comment]
I asked for cloudyvideos not promptfile.
But I tested the link and it is working on my kodi systems.

**Comment by ArcTanH** [comment]
Well, theres not a single link working, so I didn't bother searching for cloudyvideos or anything specific.
Can I provide you with any more informations to help you hunting this bug?

**Comment by Lynx187** [comment]
Well you could provide a log with "debug logging"-on, but since its working with other Kodi distributions I would guess its a problem with xbian or with your system settings.
Did you test other 3rd party streaming addons?

**Comment by Lynx187** [comment]
I just tested version 2.1.13 with Xbian for Rpi2, works.

**Comment by ArcTanH** [comment]
I don't get it, but either can't figure out what happens on my systems.
Let's close this issue for now.

2015-07-11 20:49 GMT+02:00 Lynx187 <notifications@github.com>:

> I just tested version 2.1.13 with Xbian for Rpi2, works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lynx187/plugin.video.xstream/issues/32#issuecomment-120652235>
> .
>



-- 

--
Thomas Schyra
http://thomas.schyra.net

**Comment by Lynx187** [comment]
If you activate "dabug logging" in the Kodi settings , maybe the log reveals what's going wrong when opening the stream.
If you're using profiles, tweaking your advancedsettings.xml could help http://forum.kodi.tv/showthread.php?tid=224564
But actually this is not a real issue of the addon.
