### ISSUE TITLE
XStream silently refuses to open series

### ISSUE THREAD

**Issue by tobbi** [Lynx187/plugin.video.xstream#43]
I searched for "Voyager" in order to watch Star Trek Voyager with XStream. However, it silently refuses to load the episode listing, at least for the English version of Voyager. You can find the relevant error message in the kodi.log here:
http://xbmclogs.com/pjtfbw5fj#line-2545

I'm running the latest version of XStream (2.1.14).

The directory listing should be here:
http://kinox.to/Stream/Star_Trek_Voyager.html

**Comment by Lynx187** [comment]
On the website are no season, episodes listed for Voyager (en), so there's nothing to display.
