### ISSUE TITLE
Keep trying further hosters if player fails to open valid stream link

### ISSUE THREAD

**Issue by Lynx187** [Lynx187/plugin.video.xstream#44]

**Comment by Shinoby1992** [comment]
Hey, wollte kein issue eröffnen passt hier rein. Habe in Einstellungen den Punkt aktiv das Hoster überprüft werden sollen, passiert das auch wirklich? Viele Links funktionieren nicht bei movie4k oder Kinox, ich weiß jedoch nicht ob die Files wirklich gelöscht wurden vom Hoster
Oder ob es resolverprobleme sind. Cloudtime, filenuke usw.. Hab jetzt bei spectre geschaut. Kann natürlich auch sein das überall Files gelöscht wurden was dann dummer Zufall wäre da einfach bei fast allen immer error kommt

**Comment by Lynx187** [comment]
Naja, passt nur bedingt hier rein.
Im Forum in des FAQs zu den Einstellungen steht doch drin, dass diese Einstellung "nicht unterstützte Hoster" aus der Liste entfernt und sie entsprechend ihrer Priorität sortiert. Ob der Link tatsächlich noch funktioniert wird da nicht geprüft.
Mit "automatischer Hosterwahl" wird dann solange probiert bis einer geht oder die Liste erschöpft ist.
Mit dem aktuellen Git Stand sollte es auch weiter ausprobieren wenn, ein gültiger Link dann im Player zum Timeout führt.

Ob die Datei wirklich nicht mehr existiert oder es Probleme mit dem Resolver gibt muss man dann ggf. per log und Browser gegenprüfen oder so hinnehmen.

**Comment by Shinoby1992** [comment]
scheint am urlresolver zu liegen der einfach viele Hoster nichtmehr ansteuern kann
