### ISSUE TITLE
Error in line 30!!!

### ISSUE THREAD

**Issue by sunderlandz** [Lynx187/plugin.video.xstream#54]
KeyError: 'modified'
/plugin.video.xstream/resources/lib/handler/pluginHandler.py
line 30, in getAvailablePlugin

**Comment by Viper2k4** [comment]
https://github.com/Lynx187/plugin.video.xstream/issues/54

?

**Comment by sunderlandz** [comment]
Your plugin isn't working.

When I tried to open your addon on Kodi, I get this message "KeyError: 'modified'
/plugin.video.xstream/resources/lib/handler/pluginHandler.py
line 30, in getAvailablePlugin"

**Comment by Lynx187** [comment]
Yes, but only if there is already an older pluginDB. This was already reported by sb. and I'm aware of it.
