### ISSUE TITLE
Remove movies-ever and series-ever

### ISSUE THREAD

**Issue by versable** [Lynx187/plugin.video.xstream#63]
Since they are now using the gkplugin to protect their links, I don't see any reason to keep them.
KinoLeak could also be purged since they use blazingfast.io.

**Comment by Viper2k4** [comment]
I think seberoth is working on it

https://github.com/seberoth/plugin.video.xstream/commit/c4ddc0f8db1a4cd84a773014d23f528f331dead1

**Comment by versable** [comment]
Looks promising, I'd be impressed if seberoth gets this working again.

**Comment by Lynx187** [comment]
I had a look at ME and SE (not with firefox) a couple of weeks ago, its not too difficult to get the file link. But Seberoth found a nice way to get the hoster link.

blazingfast would need a deeper look to bypass, but I'm not in the mood. I would not say its impossible per se.
