### ISSUE TITLE
Optimized Icon for MovieEver

### ISSUE THREAD

**Issue by StoneOffStones** [Lynx187/plugin.video.xstream#71]
Hallo Lynx187, hello Versable,

gehe mal davon aus das ich auch auf deutsch schreiben kann.
Ist einfacher! ;)

Habe bereits das Icon für SeriesServer in Seberoths fork beigetragen.
Wollte an dieser Stelle auch ein entsprechendes Icon für MovieEver anbieten.
![moviesever_2](https://cloud.githubusercontent.com/assets/12751497/12195590/96179eb4-b5f8-11e5-94ee-31fa555b21dc.png)

Kann auch zu anderen Icons Unterstützung anbieten :)

**Comment by versable** [comment]
Von mir aus können wir das nehmen. Die Entscheidung liegt aber nicht bei mir. Ein paar verbesserte Icons sind schon von mir eingeflossen: https://github.com/Lynx187/plugin.video.xstream/commit/40a288be42de959d1630c0252c26fe233dcf289a

**Comment by StoneOffStones** [comment]
Ist nur ein unverbindliches Angebot von meiner Seite aus.

Einen Kommentar zu den Icons hätte ich.
Man sollte aufpassen das die Informationen/Abbildungen auf den Icons nicht zu detailiert und fein sind.
Wenn diese vom Skin über die entsprechenden Viewtypes groß dargestellt werden wirken diese umscharf und wenn klein dargestellt sind diese undeutlich zu erkennen.

Also wie ist die goldene Mitte das Optimum...

**Comment by StoneOffStones** [comment]
Weitere Alternativen:

![burning_series](https://cloud.githubusercontent.com/assets/12751497/12199648/fe64bcec-b619-11e5-974c-2d949380759c.png)


![kkiste](https://cloud.githubusercontent.com/assets/12751497/12199649/016d50f2-b61a-11e5-971f-135f780726ed.png)


![kinox](https://cloud.githubusercontent.com/assets/12751497/12200301/7a144476-b61e-11e5-8d80-a61145c5ead0.png)
![kinox_mirror](https://cloud.githubusercontent.com/assets/12751497/12200306/7e5e6a5c-b61e-11e5-89ca-b6c90f6dc9bc.png)

**Comment by StoneOffStones** [comment]
Nachschlag...

![gstream](https://cloud.githubusercontent.com/assets/12751497/12200537/ab277d0c-b61f-11e5-90ea-1832721c6b84.png)

Die Entscheidung liegt bei Euch...

**Comment by versable** [comment]
Gefallen mir alle sehr gut, ich bevorzuge die Kinox-Variante ohne Spiegelung. Mach doch ein pull-request.

**Comment by StoneOffStones** [comment]
Schön das sie gefallen!

Würde wirklich liebend gerne einen PullRequest einstellen aber leider tue ich mich noch mit GitHub etwas schwer.
Wir genau gehe ich da vor?

**Comment by Viper2k4** [comment]
https://help.github.com/articles/using-pull-requests/

Kurz gesagt machst ne Foke und änderst im Foke was du ändern möchtest und dann kannst von den Änderungen quasi nen Pull machen.

**Comment by versable** [comment]
Wenn du möchtest kann ich auch ein pull-request mit deinen Icons erstellen.

**Comment by StoneOffStones** [comment]
Habe mich mal dran getraut und glaube es hinzubekommen.
Trotzdem danke für die angebotene Hilfe!

Habe da noch weitere Icons für KinoLeak.TV und bitte um kurzes Feedback.
Ich finde das ohne die Kacheln, sprich das schlichtere besser

![kinoleak](https://cloud.githubusercontent.com/assets/12751497/12216004/672ec5fa-b6d4-11e5-93f6-45aec3c049b2.png)

![kinoleak_tiles](https://cloud.githubusercontent.com/assets/12751497/12216008/6fce9942-b6d4-11e5-9842-f0c80c7d9934.png)

**Comment by versable** [comment]
Das erstere. Fast, du hast jetzt auf deiner eigenen Repo ein pull-request erstellt und auf dich selber gezogen. Mit welchem Betriebssystem und Tools arbeitest du?

**Comment by StoneOffStones** [comment]
Habe nur versucht den aktuellsten Stand von Lynx187 auf meinen zu übertragen ;)

So jetzt noch movie2k:

![movie2k_slogan](https://cloud.githubusercontent.com/assets/12751497/12216088/f6c448b4-b6d6-11e5-9c77-52f30a9b62bc.png)
![movie2k](https://cloud.githubusercontent.com/assets/12751497/12216089/f6ea34ca-b6d6-11e5-900d-c263265ff2e6.png)

**Comment by versable** [comment]
Mach mal auf dein new-icons branch:

```
git reset --hard 91dc50
git cherry-pick 581ccc
git push -f
```

**Comment by Viper2k4** [comment]
Ich habes es noch nicht geteste. Aber könnte das "KinoLeak.TV" Icon nicht etwas zu detailiert sein? Ich erkennt auf den Monitor ja schon nicht das da nen Minion am K hängt ^^

**Comment by StoneOffStones** [comment]
Wo und wie genau gebe ich die Befehle ein?!
Benutze GitHub Desktop für Mac...

Der Einwand zum KinoLeak Icon wird geprüft...

**Comment by versable** [comment]
https://help.github.com/articles/set-up-git/#platform-mac
Ansonsten kannst du mal bei IRC vorbeischauen: quakenet #xstream

**Comment by StoneOffStones** [comment]
Also irgendwie checke ich das nicht wieso ich diesen Befehl eingeben muss.
Wenn ich GitHub Desktop verwende klappt der Abgleich per Ssh doch prima. 

Zum anderen Thema:
Die KinoLeak Datei ist wenn klein dargestellt recht scharf, erst wenn sie in großen Kacheln dargestellt wird sieht es sehr unscharf aus!

Mal ne frage, spricht was dagegen die Auflösung zu verändern?!
Bei einem ersten Test sah schon bei 400x400 px die Welt viel klarer aus ;)
Wenn nicht würde ich die Icons nochmals anpassen und die Dateigröße mit ImageOptim verbessern. 
Habe da an eine Auflösung von 512x512 px gedacht.

**Comment by StoneOffStones** [comment]
Versable:

Habe den newIcons Branch gelöscht und habe es erneut über den master Branch versucht.
Wenn es immer noch nicht richtig ist würde ich, wenn alle Icons überarbeitet sind, gerne auf dein Angebot zurückkomme diese bei dir einzustellen und den Pull Request  zu erstellen :)

**Comment by versable** [comment]
Das Problem ist der commit hier: https://github.com/StoneOffStones/plugin.video.xstream/commit/cdf62d5a7a9b2d3d74d57b69eec87ea6a9e43bdb

Am besten du machst einen 'Hard Reset' auf lynx/master und dann commitest du nochmal.

**Comment by StoneOffStones** [comment]
Werde mal danach google und versuchen das durchzuführen.

Spricht was gegen die höhere Auflösung?!

**Comment by versable** [comment]
256*256 ist 'default' für Kodi als Icon

**Comment by StoneOffStones** [comment]
Habe den Fork komplett gelöscht und erstelle jetzt einen erneut.
Wenn ich jetzt die Icons hinzufüge und einen Pull Request erstelle sollte es doch klappen?!

**Comment by versable** [comment]
Jap

**Comment by StoneOffStones** [comment]
Was sagt denn Lynx187 zur höheren Auflösung.
Das macht optisch einen großen Unterschied...

**Comment by Viper2k4** [comment]
Also im xStream wird das Icon mit setThumbnail an das oGuiElement gesetzt. Und dafür gibt es für die Auflösung keine festlegung. Die 256*256 sind für das Icon des Addons wenn ich mich recht entsinne. Ich würde daher sagen man könnte durch aus 512x512 nehmen.

**Comment by Lynx187** [comment]
Ja, stimmt eigentlich gilt 256x256 das nur für das Addon-Icon, also man könnte auch etwas größer werden. Da ich persönlich für das Hauptmenu immer den Thumb-View nutze fällt die Auflösung nicht ins Gewicht, Hauptsache etwas bunt und unterscheidbar.

**Comment by StoneOffStones** [comment]
Na dann werd ich mich mal an die Arbeit machen. Habe nur auf das Feedback gewartet :) 

Zuerst haben für mich die bereits unterstützten Seiten Priorität.
Anschließend würde ich Icons für weitere potentielle Seiten erstellen, wie die gerade  von versable entwickelten.

**Comment by StoneOffStones** [comment]
So Pull Request eingereicht!

Hat jetzt doch etwas länger gedauert weil einerseits das Bildmaterial recht dürftig war und ich darüber hinaus teilweise bis zu 7 Varianten erstellt habe um anschließend alle Icons in Kodi einzuladen und die besten rauszufiltern. 

Die Finalisten wurden nicht nur aufgrund der Optik ausgewählt, mir war ebenfalls wichtig das diese im Bezug auf die eigentlichen Webseiten authentisch wirken.

Hoffe es gefällt und wünsche viel Spaß damit...

**Comment by Viper2k4** [comment]
Was hast den da in der "movie4k_to.py" noch alles geändert mit den leerzeilen und so? Das war beim letzten Pull nicht so oder?

**Comment by StoneOffStones** [comment]
?!

Eigentlich gar nichts. 
Habe nur movie2k.jpg in movie4k.png abgeändert.
Habe es in dem Editor Atom gemacht, kann das damit zusammen hängen?

**Comment by StoneOffStones** [comment]
Und nun???

**Comment by StoneOffStones** [comment]
Sorry für das Durcheinander!

Hoffe es jetzt korrekt gemacht zu haben.
Lehrjahre sind ja keine Herrenjahre ;)

**Comment by versable** [comment]
Kein Problem. Übrigends ist die Funktion von Atom (Remove trailing whitespaces, add newline at EOF) gar nicht so schlecht. Ist dann hilfreichen wenn man die commits trennt. Also, erstmal die zu bearbeitende Datei speichern, ein commit mit "Remove trailing whitespaces, at newline at EOF" machen, dann die gewünschten Änderungen tätigen und nochmal commiten.

Die neuen Icons/Logos sind super.

Grüße,

Mike

**Comment by StoneOffStones** [comment]
Danke!!!

Hab mich entschlossen das Logo für HDfilme.tv erst bereitzustellen wenn diese Seiten offiziell hinzugefügt wurden.

**Comment by versable** [comment]
Vielleicht kriegst du auch ein besseres neues Logo für XStream hin als ich, hier mein Vorschlag: https://github.com/Lynx187/plugin.video.xstream/pull/58/files

**Comment by StoneOffStones** [comment]
Sieht doch gut aus!
Aber wenn du möchtest kann ich mich daran versuchen. Gibt es etwas was zu berücksichtigen oder von hohem Wert für dich, Lynx187 bzw. alle Nutzer ist?!

Würde aber etwas Zeit in Anspruch nehmen...

**Comment by versable** [comment]
Nur 256x256. Ansonsten ist alles erlaubt. Mach wie du es möchtest, ist ja alles auf freiwilligen Basis ;)

**Comment by StoneOffStones** [comment]
Werd mich mal dran ausprobieren ich etwas Zeit habe aber wie gesagt dein Logo sieht doch schon sehr gut aus ;)

**Comment by StoneOffStones** [comment]
Wo bekommt man den Font für das X bei xStream her?
Hatte daran gedacht etwas größer darzustellen.

Davon abgesehen wäre es auch ok wenn es andere Schriftarten wären und ist das was wir hier betreiben auch im Interesse vom Masterchief (Lynx187) ;)

**Comment by versable** [comment]
Ich habe ein Bitmap trace vom alten Logo gemacht:
http://www.hasinase.de/X.svg

**Comment by Lynx187** [comment]
Da ich auch nicht das original habe, hatte das für das Forumslogo und Favicon so ähnlich gelöst wie versable. 
Für das Original müsste man evtl. mal bei DJToll aus dem Nerds Forum anfragen.
Apropos Forumslogo und Favicon, diese am besten bitte ebenfalls bereitstellen.

Ok bei weiteren Fragen zum Mainlogo bitte neuen Issue, die Fragen zu den Siteicons scheinen ja geklärt zu sein.
