### ISSUE TITLE
New Addon-Icon

### ISSUE THREAD

**Issue by StoneOffStones** [Lynx187/plugin.video.xstream#84]
Hallo miteinander,

wie bereits angedeutet kann ich mich mal an einem neuen, frischeren Icon fürs Addon versuchen.
Wollte dieses Issues nutzen um meine Fortschritte aufzuzeigen und auch eventuelles Feedback zu erfahren.

**Comment by StoneOffStones** [comment]
Vorschlag1 in mehreren Varianten und bereits in 256x256:
![v1-1](https://cloud.githubusercontent.com/assets/12751497/12593004/32c3b00c-c46f-11e5-800e-89e7698ba873.png)
![v1-2](https://cloud.githubusercontent.com/assets/12751497/12593008/387fd566-c46f-11e5-8809-39398867d275.png)
![v1-3](https://cloud.githubusercontent.com/assets/12751497/12593018/3d4e18d2-c46f-11e5-9cdd-f752d4aa7328.png)
![v1-4](https://cloud.githubusercontent.com/assets/12751497/12593022/42193b3a-c46f-11e5-9076-3cff63134c90.png)
![v1-5](https://cloud.githubusercontent.com/assets/12751497/12593028/46503bea-c46f-11e5-8ec3-292f488e4fc1.png)

**Comment by StoneOffStones** [comment]
Vorschlag2 mit etwas gravierenderen Unterschieden zueinander:
![v2-1](https://cloud.githubusercontent.com/assets/12751497/12593578/0fe72318-c472-11e5-9d13-eb2a43939a2d.png)
![v2-2](https://cloud.githubusercontent.com/assets/12751497/12593577/0fe40c5a-c472-11e5-9dc1-e59ca2b5f8b7.png)

**Comment by StoneOffStones** [comment]
Für mehr reicht nicht die Zeit.
Was haltet ihr davon?!
Bin für Ratschläge, Ideen und Verbesserungen offen...

**Comment by Pooky** [comment]
Die letzte logo gefällt mir sehr, nice work! :+1:

**Comment by Lynx187** [comment]
Das vorletzte also das 6. gefällt mir von der Art her. Hat gewisse Ähnlichkeit mit dem derzeitigen ist aber einfacher, ohne viel drumherum. 

Der Name wirkt aber nicht so präsent wie bei denen davor.
Den Übergang zum schwarz würde ich vllt beim Icon weglassen oder schwächen/schmaler machen. Bei einem Hintergrund/Fanart wäre das kein Problem.

**Comment by StoneOffStones** [comment]
Ich muss auch sagen, dass ich das vorletzte priorisiere. Auch das mit den schwarzen Rändern ist mir im Nachhinein aufgefallen. ;)
Waren ja auch erstmal nur Schüsse ins Leere.

Mir ist noch eine Idee gekommen.
Stellt euch Scheinwerferlicht vor das sich kreuzt und das würde das X darstellen. Die Schrift (Stream) würde dann ähnlich schlicht und minimalistisch dahinter angehängt werden. 
Was denkt ihr?!
Weiß zwar noch nicht genau wie ich das mit dem Spotlights hinkriege aber wollte mal die Idee vorstellen.

Zu guter letzt stellt sich die Frage ob eigentlich auch ein neues Fanart her soll?!

**Comment by StoneOffStones** [comment]
Zur Vollständigkeit halber aus einem bereits geschlossenen Issue:

versable:

Ich habe ein Bitmap trace vom alten Logo gemacht:
http://www.hasinase.de/X.svg

Lynx187:

Da ich auch nicht das original habe, hatte das für das Forumslogo und Favicon so ähnlich gelöst wie versable. 
Für das Original müsste man evtl. mal bei DJToll aus dem Nerds Forum anfragen.
Apropos Forumslogo und Favicon, diese am besten bitte ebenfalls bereitstellen.

Ok bei weiteren Fragen zum Mainlogo bitte neuen Issue, die Fragen zu den Siteicons scheinen ja geklärt zu sein.

**Comment by StoneOffStones** [comment]
Vorschlag3:

Das X Steht schon! Hier geht es jetzt um die eigentliche Anordnung und die jeweilige Schriftart?!
Habe meine Favoriten aber ich möchte nicht beeinflussen ;)
Bitte um Feedback...

![1](https://cloud.githubusercontent.com/assets/12751497/12626356/941a8a1e-c538-11e5-940d-179807800a29.png)
![2](https://cloud.githubusercontent.com/assets/12751497/12626359/943e3b94-c538-11e5-99c5-0673e87ca9ff.png)
![3](https://cloud.githubusercontent.com/assets/12751497/12626360/943e5552-c538-11e5-9426-8753135eb62a.png)
![4](https://cloud.githubusercontent.com/assets/12751497/12626361/9440cb34-c538-11e5-934d-3d945d3eebf6.png)
![5](https://cloud.githubusercontent.com/assets/12751497/12626358/943dc22c-c538-11e5-9e4d-4a744744d478.png)
![6](https://cloud.githubusercontent.com/assets/12751497/12626363/94563424-c538-11e5-90f4-5296aa918c69.png)
![7](https://cloud.githubusercontent.com/assets/12751497/12626357/9433fd28-c538-11e5-965a-6f3cc3877103.png)
![8](https://cloud.githubusercontent.com/assets/12751497/12626362/94520228-c538-11e5-98e6-11b647026f7e.png)
![9](https://cloud.githubusercontent.com/assets/12751497/12626364/9457a2f0-c538-11e5-9b3f-dd879dbd2187.png)
![10](https://cloud.githubusercontent.com/assets/12751497/12626365/94597c74-c538-11e5-800e-3268c78ce4b1.png)

**Comment by StoneOffStones** [comment]
Als letzten entscheidenden Punkt geht es noch um den Hintergrund:
Sind alle recht schlicht gewählt, bitte ebenfalls um Mitbestimmung!

![icon_back1](https://cloud.githubusercontent.com/assets/12751497/12626510/52657ec0-c539-11e5-9735-c4cedfc6dddd.png)
![icon_back2](https://cloud.githubusercontent.com/assets/12751497/12626512/5299bf64-c539-11e5-868d-47f4385dd1d3.png)
![icon_back3](https://cloud.githubusercontent.com/assets/12751497/12626513/529d53b8-c539-11e5-8333-c8ff654ef224.png)
![icon_back4](https://cloud.githubusercontent.com/assets/12751497/12626514/529f0ea6-c539-11e5-9de8-48c5bb3c9740.png)
![icon_back5](https://cloud.githubusercontent.com/assets/12751497/12626515/52a0b62a-c539-11e5-8e2e-3a2a923fce7c.png)
![icon_back6](https://cloud.githubusercontent.com/assets/12751497/12626516/52b90c2a-c539-11e5-9015-a52f999ff573.png)
![icon_back7](https://cloud.githubusercontent.com/assets/12751497/12626511/528498fa-c539-11e5-916c-90edd24f823e.png)

**Comment by StoneOffStones** [comment]
Da kein Feedback kam habe ich selber selektiert.
Das sind die Favoriten!
Nun Brauche ich euer Votum...

![3](https://cloud.githubusercontent.com/assets/12751497/12697611/aff5e1dc-c788-11e5-8375-d4824c5ab173.png)
![5](https://cloud.githubusercontent.com/assets/12751497/12697612/b0203766-c788-11e5-9f40-19d3c39affa1.png)
![8](https://cloud.githubusercontent.com/assets/12751497/12697614/b02525e6-c788-11e5-8b8a-3a3d1e2eb1c7.png)
![10](https://cloud.githubusercontent.com/assets/12751497/12697613/b021b0c8-c788-11e5-9f9e-75328970ecbf.png)

**Comment by StoneOffStones** [comment]
Mein Favorite ist das Zweite von oben...

**Comment by StoneOffStones** [comment]
Als ich eben alle Logos in Kodi durchgetestet habe ist mir aufgefallen das andere Addons wie ExtendedInfo ein viel schärferes Icon habe.
Daraufhin habe ich nachgesehen wie das sein kann und man sehe und staune das Addon-Logo ist ebenfalls in 512x512 px.
Bei xStream gibt es auch kein Problem wenn ich es höher skaliere!
Also sobald die Entscheidung steht und keine Einwände da sind wird der jeweilige PullRequest eingereicht ;)

**Comment by versable** [comment]
Hau doch die Dinger in das Forum. Mir geffällt das hier:


![](https://cloud.githubusercontent.com/assets/12751497/12626365/94597c74-c538-11e5-800e-3268c78ce4b1.png)

**Comment by StoneOffStones** [comment]
Mal sehen, vielleicht mache ich das heute Abend. Bin immer etwas vorsichtig. Weiß nicht ob es die eigentliche Entscheidungsfindung einfacher macht.

Gibt es im Forum eine Möglichkeit Abstimmungen ein einzustellen?

**Comment by Lynx187** [comment]
Bin auch für das https://cloud.githubusercontent.com/assets/12751497/12626365/94597c74-c538-11e5-800e-3268c78ce4b1.png oder das https://cloud.githubusercontent.com/assets/12751497/12697612/b0203766-c788-11e5-9f40-19d3c39affa1.png

Mit rötlichem X fände ich die besser.

**Comment by StoneOffStones** [comment]
So nach ein bisschen hin und her wäre das mein finaler Vorschlag!

![3](https://cloud.githubusercontent.com/assets/12751497/12727196/1a4d0ca6-c91c-11e5-8d7a-a734ae156a2e.png)

**Comment by Lynx187** [comment]
Ja das hat was.
Inzwischen glaube ich jetzt auch zu wissen woher das X stammt, in gewisser Weise.
Stichwort Luftfilter *g*

**Comment by StoneOffStones** [comment]
Das x habe ich nirgends abgekupfert. War einfach nur ein Template in meinem Programm was mit zugesagt hat und eine gewisse Ähnlichkeit mit dem alten Icon aufweist.

**Comment by versable** [comment]
Hast du das Bild hier:

![image](https://cloud.githubusercontent.com/assets/4646630/12748721/6f87cdd8-c9ac-11e5-9c06-e1a1f6ec1219.png)

Als SVG vorliegen?

**Comment by Lynx187** [comment]
War auch auf das ursprüngliche x bezogen.

**Comment by StoneOffStones** [comment]
Gibt es noch Wünsche/Verbesserungsvorschläge?

**Comment by Lynx187** [comment]
Hm höchstens noch mal ne Variante mit großem S zum Vergelich

**Comment by StoneOffStones** [comment]
Ist als PNG abgelegt. Muss schauen ob ich aus dem Programm heraus erzeugen kann.
Wieso was hast du vor?

**Comment by StoneOffStones** [comment]
Hab mal eben nachgesehen.
Habe mit Logoist gearbeitet und das unterstützt den SVG-Export!

Problem ist nur, das ich gerade beruflich unterwegs bin und frühestens am Donnertag die Datei bereitstellen könnte...

**Comment by StoneOffStones** [comment]
Ein größes "S" habe ich auch im Vorfeld ausprobiert. 
Meine Frau und ich haben diese Version (kleines "s") für besser empfunden!

Könnte ich auch frühestens Donnerstag zum Vergleich hochladen...

**Comment by versable** [comment]
SVG hat seine Vorteile, da es auf Vektoren und nicht Pixel basiert. Kurzum, man kann so viel 'reinzoomen' wie man möchte ohne Qualitätsverlust. Zum anderen unterstützen viele Programme SVGs zur weiteren Bearbeitung/Anpassung. Mit einem PNG/JPEG hat man die Probleme das die 'Layers' nicht exportiert werden, sondern nur die reinen Pixel. PNG/JPEGS sind der reine 'Kuchen', wobei ein SVG das Rezept ist und der Renderer der Bäcker.

**Comment by StoneOffStones** [comment]
Den Unterschied kenne ich, aber danke für die detaillierte Ausführung. ;)

Habe mit Absicht PNG für das Logo gewählt weil ich davon ausgegangen bin, dass Kodi mit Vektor basierenden Daten nicht umgehen kann.
Oder geht es dabei eher um die zukünftige Möglichkeiten und Einsatzfelder?!

**Comment by StoneOffStones** [comment]
Wenn ich heute die Daten nachreichen sollte, wie soll ich die Datei bereitstellen?
Als Pull Request und wenn ja soll die SVG auch in das Addon abgelegt werden?

**Comment by Lynx187** [comment]
Svg wäre zwar praktisch hat aber im Addon selbst eigentlich nichts verloren.
Evtl. kannst du eine Seite im Wiki anlegen, vllt. kann man es dort ablegen, müsste man mal probieren.

**Comment by StoneOffStones** [comment]
So hier nochmals die unterschiedliche Ausführung der Schrift für "Stream".
Ich muss für meinen Teil weiterhin bestätigen das mir die klein geschriebene Ausführung am meisten zusagt!

![1](https://cloud.githubusercontent.com/assets/12751497/12821898/bc49b4a0-cb65-11e5-8556-0b79ab4fe68f.png)
![2](https://cloud.githubusercontent.com/assets/12751497/12821900/bc9a4a0a-cb65-11e5-85af-cb2e687ad299.png)
![3](https://cloud.githubusercontent.com/assets/12751497/12821899/bc8569fa-cb65-11e5-8332-9d27b548ed39.png)

**Comment by StoneOffStones** [comment]
Welches Wiki meinst du genau?!

**Comment by Lynx187** [comment]
Dieses https://github.com/Lynx187/plugin.video.xstream/wiki

**Comment by StoneOffStones** [comment]
Alles klar, welches Ausführung der Schrift soll es eurer Meinung werden?!

**Comment by StoneOffStones** [comment]
Gehe einfach mal davon aus, dass die ursprüngliche Idee (Stream komplett klein geschrieben) so ok ist. Wenn keine Einwände da sind spricht das für Zustimmung. ;)

Werde den Pull Request dann so einreichen...

**Comment by StoneOffStones** [comment]
Keine Berechtigungen um in der Wiki was anzupassen!
Angemeldet bin ich natürlich ;)

![bildschirmfoto 2016-02-05 um 16 32 21](https://cloud.githubusercontent.com/assets/12751497/12850679/3697d65e-cc26-11e5-83c3-9fd50e7add63.png)

**Comment by Lynx187** [comment]
jetzt sollte es wieder gehen

**Comment by Lynx187** [comment]
Ich würde vermutlich das mit dem großen S nehmen, im Addonnamen ist das ja auch groß.

**Comment by StoneOffStones** [comment]
Danke!

Mit dem"Stream" ganz sicher?!
Das Design vieler Logos stimmt sehr häufig auf diese Art und Weise nicht mit der eigentlichen Namensgebung überein.

**Comment by StoneOffStones** [comment]
Da spielt auch mit rein, dass das X von xStream immer klein geschrieben wird aber trotzdem beim alten und "neuen" Logo das größte Element war/ist.

Bitte rein optisch bewerten ;)

**Comment by StoneOffStones** [comment]
Wenn ich die Info habe kann ich den Pull Request lassen/anpassen und das Favicon bzw. Logo für Homepage bereitstellen.

Könnte ich dann ebenfalls in der Wiki einpflegen...

**Comment by StoneOffStones** [comment]
Nach wie vor das selbe Problem!

![bildschirmfoto 2016-02-07 um 09 56 31](https://cloud.githubusercontent.com/assets/12751497/12871543/1dae44a0-cd81-11e5-8dbe-eefcbd72d408.png)

**Comment by StoneOffStones** [comment]
Hab das jetzt mal ausprobiert:

Hat damit zu tun, dass ich keine beliebigen Dateien, bei mir SVG Daten, hochladen kann.
Sondern in dem Bereich sogenannte .MD Daten angelegt werden.

**Comment by StoneOffStones** [comment]
Hab mich getäuscht!

geht selbst dann nicht wenn ich das "Rezept" aus der SVG in Textform hochladen will!

**Comment by StoneOffStones** [comment]
Bitte mal schauen ob es so ok ist?!

**Comment by StoneOffStones** [comment]
Bezüglich Bildmaterial für die Website und Vektor Grafiken habe ich ein eigenes Git erstellt in der die Daten abgelegt sind.

[https://github.com/StoneOffStones/wiki.xstream](url)

Favicons von 16x16 bis 64x64 und Logo für die Website in zwei Größen.

**Comment by StoneOffStones** [comment]
Der neue Look wurde soeben im Forum unter folgendem Pfad vorgestellt.

[http://xstream-addon.square7.ch/showthread.php?tid=567&pid=2573#pid2573](url)

Eine Frage am Rande, sind die letzten Pull Request von mir richtig eingereicht worden?!

**Comment by Lynx187** [comment]
Hättest du nicht machen brauchen aber ok.
Ja die PR passen soweit.

**Comment by StoneOffStones** [comment]
Werde das Wiki dann final anpassen wenn die Pull Requests angenommen wurden und die Optik steht. 
Vorher macht es in meinen Augen noch keinen Sinn weil der Eintag dann auch nichts repräsentieren würde. ;)

**Comment by StoneOffStones** [comment]
Außerdem sind mir noch zwei kleine Bugs/Verbesserungspotentiale bei den Icons für Kinox und G-Stream aufgefallen. 

Wird heute Nachmittag nachgereicht...
