### ISSUE TITLE
New Fanart

### ISSUE THREAD

**Issue by StoneOffStones** [Lynx187/plugin.video.xstream#85]
Um das ganze noch komplett zu machen und den immer größer werdenden Bildschirme bzw. höheren Auflösungen gerecht zu werden habe ich mich auf die Suche nach passenden Fanarts gemacht.
Habe anstatt der normalen HD Auflösung auf fullHD gesetzt.

Ich hoffe das für das Addon-Team (Lynx187) ok?!

Server:
![fanart4](https://cloud.githubusercontent.com/assets/12751497/12698348/e344fc50-c79a-11e5-9721-0b9629f87b1a.jpg)
![fanart5](https://cloud.githubusercontent.com/assets/12751497/12698349/e49f963c-c79a-11e5-9655-cc1707209c38.jpg)
![fanart6](https://cloud.githubusercontent.com/assets/12751497/12698350/e62744aa-c79a-11e5-8b5a-11b31ba14627.jpg)

Kabel:
![fanart3 1](https://cloud.githubusercontent.com/assets/12751497/12698365/284a5cd2-c79b-11e5-8083-51cac3869d59.jpg)
![fanart3](https://cloud.githubusercontent.com/assets/12751497/12698368/29bb9b8a-c79b-11e5-930f-e982ca834a9a.jpg)
![fanart2](https://cloud.githubusercontent.com/assets/12751497/12698370/2ae86fce-c79b-11e5-899b-4730efcb9793.jpg)

Code:
![fanart1](https://cloud.githubusercontent.com/assets/12751497/12698359/07e81998-c79b-11e5-84f4-b62735aa8f16.jpg)

Spotlight:
![fanart7](https://cloud.githubusercontent.com/assets/12751497/12698357/0168d422-c79b-11e5-8700-ecc67c0f5d4e.jpg)

**Comment by StoneOffStones** [comment]
Noch einer...
![fanart8](https://cloud.githubusercontent.com/assets/12751497/12698474/4f7af85a-c79d-11e5-88c4-f22ee504c581.jpg)

**Comment by Lynx187** [comment]
Kodi emphielt eigentlich ein 720p jpeg für das Fanart. Man muss auch bedenken das landet mit in der zip und wird also bei jedem Update wieder heruntergeladen. Außerdem stellt sich die Frage, wenn man den Unterschied von 720 zu 1080 sieht und sich daran stört, wieso benutzt man dann ein Streamingaddon.

An diesem Serverhintergrund wollte ich eigentlich nicht festhalten. Eher etwas in der Art http://i2.wp.com/cdn.bgr.com/2015/05/streaming-tv-2.jpg?w=625
Oder einfach das Addonlogo in groß.

**Comment by StoneOffStones** [comment]
Danke!
Gut zu wissen in welche Richtung es gehen soll.
Ich verstehe das mit den Kodi-Vorgaben aber in Anbetracht neuer hochauflösender Displays, 4K und Co, sollte man sich dem
Trend anpassen.
Deshalb auch mein Blick auf andere große Addons wie ExtendedInfo.

Icon: 512x512px
Fanart: 1920x1089px

Um zusätzlich die Datei so klein wie möglich zu gestallten habe ich das Programm ImageOptim in Gebrauch!

**Comment by StoneOffStones** [comment]
Media:

![8d863d2276f77f33cbefe222a5eab52f0af05a8611763ec7f0871233b1ec547d_-original](https://cloud.githubusercontent.com/assets/12751497/12728086/7b93bbaa-c920-11e5-8e8f-ebf1a094f7bc.jpeg)
![global-tv](https://cloud.githubusercontent.com/assets/12751497/12728102/8b6f481e-c920-11e5-8b56-8bf7115dc661.jpg)
![cool-design-wallpaper-cool-design-desktop-wallpaper-5407-](https://cloud.githubusercontent.com/assets/12751497/12728123/9ede6998-c920-11e5-90ea-4b7e43bdbccd.jpg)
![istock_000022095936large](https://cloud.githubusercontent.com/assets/12751497/12728130/a61989ae-c920-11e5-8ffd-dd885c810a01.jpg)
![media_02](https://cloud.githubusercontent.com/assets/12751497/12728131/a8b58b7c-c920-11e5-9836-b53149d7b578.jpg)
![media-wall-1600x700_c](https://cloud.githubusercontent.com/assets/12751497/12728134/aaddea02-c920-11e5-96ea-a7d975b09c6c.jpg)
![o-media-facebook](https://cloud.githubusercontent.com/assets/12751497/12728151/b64b6cca-c920-11e5-9698-191cfb4e3b89.jpg)
![slide2](https://cloud.githubusercontent.com/assets/12751497/12728177/d46c79d8-c920-11e5-9f41-63cae525ac68.jpg)
<img width="1320" alt="slider-3-multimedia" src="https://cloud.githubusercontent.com/assets/12751497/12728179/d6568bb2-c920-11e5-95f7-0086ec61d4d1.png">
![cool-designs-wallpaper-cool-design-desktop-wallpaper-1880-](https://cloud.githubusercontent.com/assets/12751497/12728185/e04ad3bc-c920-11e5-8937-c84d59f5065c.jpg)
 
oder auch die Spotlights im Beitrag davor (letztes Bild)

**Comment by StoneOffStones** [comment]
Mal die Besten in Kodi eingesetzt. (Verwende den Skin fTV)

![bildschirmfoto 2016-02-04 um 17 58 35](https://cloud.githubusercontent.com/assets/12751497/12825711/f07ccf8e-cb77-11e5-959e-479396f3aa14.png)
![bildschirmfoto 2016-02-04 um 17 59 52](https://cloud.githubusercontent.com/assets/12751497/12825712/f0ab21fe-cb77-11e5-9967-401e292f8c98.png)
![bildschirmfoto 2016-02-04 um 19 43 01](https://cloud.githubusercontent.com/assets/12751497/12825715/f0b684b8-cb77-11e5-8592-aa242516a6c8.png)
![bildschirmfoto 2016-02-04 um 19 44 01](https://cloud.githubusercontent.com/assets/12751497/12825714/f0b26aa4-cb77-11e5-9a1a-67036a475b17.png)
![bildschirmfoto 2016-02-04 um 19 44 41](https://cloud.githubusercontent.com/assets/12751497/12825713/f0afcccc-cb77-11e5-803d-02f60b9d7af8.png)

**Comment by StoneOffStones** [comment]
![bildschirmfoto 2016-02-04 um 19 50 54](https://cloud.githubusercontent.com/assets/12751497/12825861/a56ebcae-cb78-11e5-8f39-077152967dc4.png)

**Comment by StoneOffStones** [comment]
Bin über jede Beteiligung sehr dankbar.
Auch gerne neue Pics vorschlagen...

**Comment by StoneOffStones** [comment]
Schlichter Hintergrund mit Aden-Icon

![background2](https://cloud.githubusercontent.com/assets/12751497/12851079/414d96e0-cc28-11e5-9e31-7cf5f188892d.jpg)

![background1](https://cloud.githubusercontent.com/assets/12751497/12851078/41489636-cc28-11e5-849d-6340a215fd0f.jpg)

**Comment by StoneOffStones** [comment]
In Kodi...

![bildschirmfoto 2016-02-05 um 16 50 28](https://cloud.githubusercontent.com/assets/12751497/12851175/c133db4e-cc28-11e5-8108-042ed3d69967.png)
![bildschirmfoto 2016-02-05 um 16 51 05](https://cloud.githubusercontent.com/assets/12751497/12851177/c158998e-cc28-11e5-8f9b-21484442e5e7.png)

**Comment by StoneOffStones** [comment]
Noch mehr Vorschläge...

![fanart4](https://cloud.githubusercontent.com/assets/12751497/12852068/8009a9aa-cc2d-11e5-8861-cdb1e626a96b.jpg)
![fanart1](https://cloud.githubusercontent.com/assets/12751497/12852069/802eb006-cc2d-11e5-8a97-fe967e3ba908.jpg)
![fanart2](https://cloud.githubusercontent.com/assets/12751497/12852071/8032a2e2-cc2d-11e5-9b0d-22af81bda9f6.jpg)
![fanart3](https://cloud.githubusercontent.com/assets/12751497/12852070/80315d60-cc2d-11e5-9bba-cb27a8f1a6d3.jpg)

Und in Kodi...

![bildschirmfoto 2016-02-05 um 17 19 59](https://cloud.githubusercontent.com/assets/12751497/12852087/8c9b9890-cc2d-11e5-8b83-a339c92086b7.png)
![bildschirmfoto 2016-02-05 um 17 20 50](https://cloud.githubusercontent.com/assets/12751497/12852085/8c98ce26-cc2d-11e5-9ca1-a269705a0317.png)
![bildschirmfoto 2016-02-05 um 17 24 27](https://cloud.githubusercontent.com/assets/12751497/12852086/8c998438-cc2d-11e5-8c33-ad0cd896046a.png)
![bildschirmfoto 2016-02-05 um 17 25 00](https://cloud.githubusercontent.com/assets/12751497/12852084/8c97023a-cc2d-11e5-950d-50e159457477.png)

Finde den Stream mit 0 und 1 von oben kommend ganz gut.
Vielleicht noch etwas die Farbe raus nehmen und das Logo drauf ;)

**Comment by Lynx187** [comment]
Einfach nur das Addonlogo sieht auch gut aus. 
0 und 1 naja wenn dann sollte es schon einen Bezug zum Inhalt haben.
Für mehr Individualität könnte man über Themes nachdenken.

**Comment by StoneOffStones** [comment]
Themes?

**Comment by StoneOffStones** [comment]
Meinst du mit Themes, dass es ein Standard Hintergrund mit der Schrift gibt und wenn man die jeweiligen Seiten auswählt ein neuer farblich/inhaltlich passender Hintergrund einblendet?
Wenn ja finde ich die Idee nicht schlecht!

**Comment by StoneOffStones** [comment]
Habe mich an den zweiten Vorschlag für das neue Icon erinnert wo ich einen Hintergrund im Icon gewählt habe der fürs Icon unpassend war aber für ein Fanart, aufgrund der schwarzen Ränder, durchaus angemessen ist.

Next One...

![fanart3](https://cloud.githubusercontent.com/assets/12751497/12871513/1a569336-cd7f-11e5-83fa-7f1f3b7b45c7.jpg)
![bildschirmfoto 2016-02-07 um 09 37 01](https://cloud.githubusercontent.com/assets/12751497/12871514/1efb93dc-cd7f-11e5-8852-c4637e17bf9b.png)
![bildschirmfoto 2016-02-07 um 09 36 13](https://cloud.githubusercontent.com/assets/12751497/12871515/1f1dc1d2-cd7f-11e5-9213-3407ba9b447e.png)

**Comment by StoneOffStones** [comment]
Das letzte Favart ist in meinen Augen der finale Vorschlag!!!

**Comment by StoneOffStones** [comment]
Hallo Lynx187,

Soll ich die helle Version vom Fanart auch bereitstellen? Vielleicht kann man das so umsetzen, dass der User zwischen einem light- oder dark-Mode wählen kann. Dann könnte man das Fanart dem verwendeten Skin anpassen. 

Was ist aus der Idee zu den Themes geworden? Soll ich das weiter verfolgen.
Leider bräuchte ich da Hilfe da ich nicht des Programmierens mächtig bin

Letzter Punkt, wann wolltest du den neuen Look übernehmen? Verfolgst du da einen Gedanken, sprich wartest du noch auf andere Features?
