### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by sraedler** [Lynx187/plugin.video.xstream#90]
Hey, erstmal ein riesen lob an das Plugin, ist wirklich sehr gut :+1:  

Jetzt zu meiner Featureanfrage, wie wäre es, wenn man eine update Funktion einbaut, welche über gitPython die neuste Pluginversion von Github pullt?

Somit könnte man sehr schnell neue Versionen testen bzw. bei website updates würde es keine probleme geben diese zu verteilen.

**Comment by Lynx187** [comment]
Könnte man.
Wie ich im Forum schon geschrieben haben wäre gitPython für diese einzelne Sache allerdings schon etwas zu viel des Guten.
Und "testen" naja... wohl eher "nutzen".

**Comment by sraedler** [comment]
Ich hab jetzt 4 Stunden versucht etwas hinzukriegen und immer hab ich das problem, dass ich keine komplette lib wie pygit2 einbinden kann...

und finde bisher auch keine passende lib um git pulls durchzuführen ohne dass git installiert sein muss


jemand eine idee?

**Comment by Lynx187** [comment]
Damit das auf allen Plattformen Läuft müsstest du das gesamte package anls separates Addon erstellen oder komplett mit in das Addon packen, wenn dann noch binaries dabei sind...
Also mit pull ist hier ja kein echter git pull gemeint sonder einfach nur das herunterladen der zip etc.
Infos über einen Brach in disem fall der master Brach erhält man entweder indem man die html seite parst oder über die api  `https://api.github.com/repos/:user/:reponame/branches{/branch} ` 
Damit kann man prüfen obs es was neues gab.
Die Adresse der zip ist ja immer gleich, also ist der download dann keine große Hürde mehr.

**Comment by sraedler** [comment]
Ich denk bis zur Lösungsfindung können wir auch in dem [Thread](http://xstream-addon.square7.ch/showthread.php?tid=453) drüber diskutieren

**Comment by Lynx187** [comment]
Passt hier aber eher hin als in den Wünschebereich

**Comment by sraedler** [comment]
Kann mir jemand sagen wie ich die download Funktion aufrufe um beispielsweise diese Datei an einen bestimmten Ort downloade?

[https://raw.githubusercontent.com/Zanzibar82/plugin.video.streamondemand/master/version.xml](https://raw.githubusercontent.com/Zanzibar82/plugin.video.streamondemand/master/version.xml)


wenn es keine einfache Lösung gibt die download anzusprechen werde ich wget nutzen.

**Comment by Lynx187** [comment]
Welche download funktion? Die von xStream findet sich unter:  plugin.video.xstream/resources/lib/download.py
Deine Beispieldatei kann man aber ganz normal per `urlopen` laden und ihren Inhalt dann z.B. mittels `file` und `write` irgendwohin speichern.
